services:
  selenium:
    image: ${SELENIUM_IMAGE}
    ports:
      - ${SELENIUM_PORT}:4444

  spring-app:
    image: jun/${SERVICE_NAME}
    environment:
      WEBDRIVER_REMOTE_URL: http://selenium:4444
    ports:
      - ${SERVER_PORT}:8080
