volumes:
  ita-volume:

services:
  postgres:
    image: 'postgres:16.2'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${service_name}
      - POSTGRES_USER=${username}
      - POSTGRES_PASSWORD=${password}
      - TZ=Asia/Seoul
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ita-volume:/var/lib/postgresql/data

  selenium:
    image: 'selenium/standalone-chrome:127.0.6533.99'
    ports:
      - "4444:4444"
