volumes:
  ita-volume:

services:
  postgres:
    image: 'postgres:16.2'
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${service_name}
      - POSTGRES_USER=${username}
      - POSTGRES_PASSWORD=${password}

  spring-app:
    build:
      context: .
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://${db}:5432/${service_name}
        - SPRING_PROFILES_ACTIVE=local
        - SPRING_DATASOURCE_USERNAME=${username}
        - SPRING_DATASOURCE_PASSWORD=${password}
    command: ./gradlew --build-cache build -i
    volumes:
      - ./.gradle:/root/.gradle
      - ./build:/app/build
    ports:
      - '8080:8080'
