volumes:
  ita-volume:

services:
  postgres:
    image: 'postgres:16.2'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${service_name}
      - POSTGRES_USER=${username}
      - POSTGRES_PASSWORD=${password}
      - TZ=Asia/Seoul
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ita-volume:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    environment:
      FLYWAY_URL: jdbc:postgresql://${db}:5432/${service_name}
      FLYWAY_USER: test
      FLYWAY_PASSWORD: test
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - postgres
    command: [ "migrate" ]
