volumes:
  ita-volume:

services:
  postgresql:
    image: ${DB_IMAGE}
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=insta_tistory_automator_server
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - TZ=Asia/Seoul
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ita-volume:/var/lib/postgresql/data

  selenium:
    image: ${SELENIUM_IMAGE}
    ports:
      - ${SELENIUM_PORT}:4444
