spring:
  datasource:
    url: jdbc:${DB}://${DB}:${DB_PORT}/${SERVICE_NAME}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  flyway:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

webdriver:
  arguments:
    - --lang=ko
  remote-url: http://localhost:4444

schedule:
  cron:
    insta-tistory-automator: 0 * * * * * # every minute
