spring:
  datasource:
    url: jdbc:${DB}://${DB}:${DB_PORT}/insta_tistory_automator_server
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  flyway:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

webdriver:
  arguments:
    - --lang=ko
  remote-url: http://localhost:${SELENIUM_PORT}

schedule:
  cron:
    insta-tistory-automator: 0 * * * * * # every minute
