spring:
  application:
    name: InstaTistoryAutomator

insta:
  base-url: https://graph.instagram.com
  api-version: v20.0
  media-fields:
    - id
    - media_type
    - media_url
    - caption
    - permalink
    - timestamp

tistory:
  entry-url: https://nowhereland.tistory.com/manage/newpost/

webdriver:
  timeout: 3
  chrome-driver-path: src/main/resources/chromedriver
  arguments:
    - --headless=new
    - --lang=ko
