spring:
  application:
    name: InstaTistoryAutomator

insta:
  base-url: https://graph.instagram.com
  api-version: v20.0
  media-fields:
    - id
    - media_type
    - media_url
    - caption
    - permalink
    - timestamp

tistory:
  url:
    AccountsKakaoLoginPage: https://accounts.kakao.com/login/?continue=https%3A%2F%2Fkauth.kakao.com%2Foauth%2Fauthorize%3Fis_popup%3Dfalse%26ka%3Dsdk%252F1.43.5%2520os%252Fjavascript%2520sdk_type%252Fjavascript%2520lang%252Fko-KR%2520device%252FLinux_x86_64%2520origin%252Fhttps%25253A%25252F%25252Fwww.tistory.com%26auth_tran_id%3D4hw4ewcggs73e6ddd834b023f24221217e370daed18m0641p9y%26response_type%3Dcode%26state%3DaHR0cHM6Ly9ub3doZXJlbGFuZC50aXN0b3J5LmNvbS9tYW5hZ2UvbmV3cG9zdC8%26redirect_uri%3Dhttps%253A%252F%252Fwww.tistory.com%252Fauth%252Fkakao%252Fredirect%26through_account%3Dtrue%26prompt%3Dselect_account%26client_id%3D3e6ddd834b023f24221217e370daed18&talk_login=hidden#login
    NowherelandTistoryManageNPage: https://nowhereland.tistory.com/manage/newpost/

webdriver:
  timeout: 3
  chrome-driver-path: src/main/resources/chromedriver
  arguments:
    - --lang=ko
