spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insta_tistory_automator
    username: test
    password: test

  flyway:
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate
