spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insta_tistory_automator
    username: test
    password: test

  flyway:
    baseline-on-migrate: true

  docker:
    compose:
      file: ./InstaTistoryAutomatorServer/compose.yaml

  jpa:
    hibernate:
      ddl-auto: validate

webdriver:
  timeout: 3
  arguments:
    - --lang=ko
