spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/insta_tistory_automator
    username: test
    password: test

  flyway:
    baseline-on-migrate: true

  docker:
    compose:
      file: InstaTistoryAutomatorServer/compose.yaml

  jpa:
    hibernate:
      ddl-auto: validate

  data:
    jdbc:
      dialect: postgresql

webdriver:
  timeout: 3
  chrome-driver-path: src/main/resources/chromedriver
  arguments:
    - --lang=ko

insta:
  base-url: http://localhost:${wiremock.server.port}