volumes:
  ita-volume:
    external: true

services:
  db:
    image: postgres:16.2
    container_name: ita-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - TZ=Asia/Seoul
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ita-volume:/var/lib/postgresql/data