spring:
  application:
    name: insta-tistory-automator-server
  profiles:
    group:
      mock-test: test
      local-test: test, local

insta:
  base-url: https://graph.instagram.com
  api-version: v20.0
  media-fields:
    - id
    - media_type
    - media_url
    - caption
    - permalink
    - timestamp

tistory:
  entry-url: https://nowhereland.tistory.com/manage/newpost/

webdriver:
  timeout: 3
  arguments:
    - --headless=new
    - --lang=ko
  remote-url: http://localhost:4444

schedule:
  cron:
    insta-tistory-automator: 0 0 11 * * * # everyday 11:00 UTC (20:00 in KTC)
