name: Java CI with Gradle

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: What do you want to deploy?
        options:
          - insta-tistory-automator-server

env:
  SERVICE_NAME: ${{ inputs.name }}
  SECRETS_KEY: "SECRETS_JSON"
  SECRETS_FILE: "secrets.json"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.name }}

      - uses: actions/cache@v4
        with:
          path: |
            ./.gradle
            ./build
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-

      - name: Gradle build
        run: docker compose --env-file=.env -f ci/compose.yaml up --build --abort-on-container-exit --force-recreate

      - name: Configure AWS Credentials@v4
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: 'sts.amazonaws.com'
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Setup secrets
        run: |
          echo "${{ toJson(secrets) }}" >> ${{ env.SECRETS_FILE }}

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          secret-files: ${{ env.SECRETS_KEY }}=${{ env.SECRETS_FILE }}
          tags: ${{ secrets.ECR_HOST }}/${{ env.SERVICE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max

      - name: Clean up
        if: always()
        run: |
          rm -f ${{ env.SECRET_FILE }}
