name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: What do you want to deploy?
        options:
          - InstaTistoryAutomatorServer

env:
  SERVICE_NAME: ${{ inputs.name }}
  SECRET_FILE: "secret.txt"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.name }}

      - name: Change directory to the target directory
        run: cd ${{ inputs.name }}

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup secrets
        run: |
          echo "${{ toJson(secrets) }}" > secrets.json

      - name: Gradle build
        run: docker compose --env-file=.env -f ci/compose.yaml up --build --abort-on-container-exit --force-recreate

      - name: Build docker image
        run: docker build -f cd/Dockerfile -t jun/$SERVICE_NAME --secret id=BUILD_SECRET,src=secrets.json --progress=plain --no-cache .