name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: What do you want to deploy?
        options:
          - InstaTistoryAutomatorServer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.name }}

      - name: Change directory to the target directory
        run: cd ${{ inputs.name }}

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Setup secrets
        run: |
          secrets=${{ toJson(secrets) }}
          echo "$secrets" | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while IFS= read -r line; do
            key=$(echo "$line" | cut -d= -f1)
            value=$(echo "$line" | cut -d= -f2)
            export "$key=$value"
            echo "Exporting $key"
          done

      - name: Gradle build
        run: docker compose --env-file=.env -f ci/compose.yaml up --build --abort-on-container-exit --force-recreate

      - name: Build docker image
        run: docker compose --env-file=.env -f cd/compose.yaml build