name: Java CI with Gradle

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: What do you want to deploy?
        options:
          - insta-tistory-automator-server

env:
  SERVICE_NAME: ${{ inputs.name }}
  SECRET_FILE: "secret"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.name }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Gradle build
        run: docker compose --env-file=.env -f ci/compose.yaml up --build --abort-on-container-exit --force-recreate

      - name: Configure AWS Credentials@v4
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: 'sts.amazonaws.com'
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}

      - name: Setup secrets
        run: |
          echo "${{ toJson(secrets) }}" > secrets.json

      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          secret-files: BUILD_SECRET=./secrets.json
          tags: ${{ secrets.ECR_HOST }}/$SERVICE_NAME:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max