# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: What do you want to deploy?
        options:
          - InstaTistoryAutomatorServer

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      INSTA_USER_TOKEN: ${{ secrets.INSTA_USER_TOKEN }}
      INSTA_USER_ID: ${{ secrets.INSTA_USER_ID }}
      TISTORY_EMAIL: ${{ secrets.TISTORY_EMAIL }}
      TISTORY_PASSWORD: ${{ secrets.TISTORY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ${{ inputs.name }}

      # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test and build
        run: docker compose -f ${{ inputs.name }}/ci/compose.yaml up --build --abort-on-container-exit --force-recreate

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Make a docker image
        run: docker compose -f ${{ inputs.name }}/cd/compose.yaml build